# Generated by Django 5.1 on 2024-09-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfcmtoken',
            name='fcm_token',
            field=models.CharField(max_length=255),
        ),
    ]
