# Generated by Django 5.1 on 2024-09-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_userfcmtoken_last_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfcmtoken',
            name='last_notified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
