# Generated by Django 5.1 on 2024-08-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
