# Generated by Django 5.1 on 2024-09-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='markers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
