# Generated by Django 5.1 on 2024-08-28 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_is_role_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$')]),
        ),
    ]
