# Generated by Django 5.1 on 2024-09-14 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(help_text='Email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, help_text='Message', null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(help_text='Full name', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$')]),
        ),
    ]
