# Generated by Django 5.1 on 2024-09-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactus_email_alter_contactus_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, help_text='Message', max_length=600, null=True),
        ),
    ]
