# Generated by Django 5.1 on 2024-08-30 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilsensor',
            name='data',
        ),
        migrations.RemoveField(
            model_name='soilsensor',
            name='name',
        ),
        migrations.AddField(
            model_name='soilsensor',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soilsensor',
            name='nitrogen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soilsensor',
            name='phosphorus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soilsensor',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soilsensor',
            name='soil_moisture',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soilsensor',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilsensor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_sensor_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
