# Generated by Django 5.1 on 2024-08-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_device_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='access_token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
