# Generated by Django 5.1 on 2024-08-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_alter_device_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='configurations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soilsensor',
            name='npk',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soilsensor',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
