# Generated by Django 5.1 on 2024-08-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_device_configurations_soilsensor_npk_soilsensor_ph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
