# Generated by Django 5.1 on 2024-09-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
        ('sensors', '0006_alter_device_access_token_alter_device_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='fields',
            field=models.ManyToManyField(related_name='devices', to='fields.field'),
        ),
    ]
